openapi: 3.1.0
info:
  version: 1.0.0
  title: Stories app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of stories app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
  - name: Stories
    description: Stories operations.
servers:
  - url: http://localhost:3000
paths:
  /stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
